#!/bin/bash
set -x
module load gnu
tmp=`mktemp `
#nw_reroot $1 $2 > $tmp
nw_topology -I $1 > $tmp
echo "rerooting genetrees has been finished"
listS=`mktemp`
nw_labels -I $3 > $listS
listSpec=`mktemp`
for x in `cat $listS`; do
	echo "$x 1 $x"
done > $listSpec
echo "rerooted genetrees at $tmp will be used" 
echo "list of species available at $listSpec"
echo $4
$WS_HOME/DISTIQUE/src/shell/mpest $tmp $listSpec $3 $4
