#!/bin/bash
DIR=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)
show_help() {
cat << EOF
USAGE: ${0##*/} [-h] [-g GENETREES] [-t CONSENSUS THRESHOLD] [-n NUMBER OF SAMPLES] [-o OUTPATH] [ -s TRUE SPECIES TREE]
Generates a pool of branches with their posterior probabilities using Astral.

	-h	HELP		display help and exit
	-g  	GENETREES 	The gene trees filename
	-t	THRESHOLD 	The consensus threshold to generate randomly resolved samples.
	-n 	SAMPLE NUMS 	The number of replicates, generated by randomly resolving consensus tree of given genetrees.
	-o 	OUTPUT FOLDER	The output folder to put the results there.
	-s 	SPECIES TREE 	The true species tree to compare the results.
EOF
}

if [ $# -lt 1 ]; then 
	show_help
	exit 1 
fi

t=0.2;
n=10;

while getopts "hg:t:n:o:s:" opt; do
        case $opt in
        h)
                show_help
                exit 0;
                ;;
        g)
                gt=$OPTARG
                ;;
        t)
                t=$OPTARG
                ;;
        n)
                n=$OPTARG
                ;;
        o)
                out=$OPTARG
                ;;
	s)
		s=$OPTARG
		;;
	?)
		show_help
		exit 1;
		;;
	esac
done
#rm $out/*

TmpFolder=`mktemp -d`;
outTree=`mktemp -p $TmpFolder random_resolved_tree.nwk.XXXXX`

python $DIR/randomResolvedSampleGenerator.py -g $gt -o $outTree -t 0.5,0.2,0.333,0.01 -n $n
mainTmpStat=`mktemp -p $TmpFolder randomTreesStat.XXXXX`;
mainTmpTree=`mktemp -p $TmpFolder randomTreesPP.XXXXX`;
tmp=`mktemp`;
poolOfTrees=`mktemp -p $TmpFolder randomresolvedTrees.XXXXX`;
for x in `cat $outTree`; do
	y=$(echo $x | sed -e 's/\[&U\]//g')
	echo $y>$tmp
	echo $y>>$poolOfTrees
	java -Xmx2000M -jar $WS_HOME/ASTRAL/astral.4.9.1.jar -i $gt -q $tmp -t 4 >> $mainTmpTree 2>> $mainTmpStat;
done
TmpSpStat=`mktemp -p $TmpFolder spTreeStat.XXXXX`;
TmpSpTree=`mktemp -p $TmpFolder spTreePP.XXXXX`;
java -jar $WS_HOME/ASTRAL/astral.4.9.1.jar -i $s -q $s -t 2 >> $TmpSpTree 2>>$TmpSpStat;
res=`mktemp -p $TmpFolder ppOfBranches.XXXXX`;
$DIR/extractPPofPoolOfBranches.py -i $mainTmpStat -s $TmpSpStat -o $res
#$DIR/uniquePoolOfBranches.py -i $mainTmpStat -o $out;
#$DIR/checkBranchIfAvail.py -i $out/poolOfBranches.txt -o $out -s $TmpSpStat;
tar czvf $out/astral-PP.tar.gz $TmpFolder

rm $mainTmpStat
rm $TmpSpStat
rm $mainTmpTree
rm $TmpSpTree
rm $poolOfTrees
